FROM docker.elastic.co/kibana/kibana:8.11.1

ARG ELASTICSEARCH_URL=http://0.0.0.0:5100
ENV ELASTICSEARCH_URL=${ELASTICSEARCH_URL}

ARG XPACK_SECURITY_ENABLED=false
ENV XPACK_SECURITY_ENABLED=${XPACK_SECURITY_ENABLED}